/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 .\corn.glb
Author: Tiia Tuulia (https://sketchfab.com/tiiatuulia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/corn-corn-corn-10187bc37c9e42ef8770b28452ee7cd3
Title: Corn! Corn! Corn!
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Corn(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('../../modelos/corn.glb')
    const { actions } = useAnimations(animations, group)
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.7}>
                    <group name="fdd38405c86b44e49e5f7a62b0d2f0f7fbx" rotation={[Math.PI / 2, 0, 0]}>
                        <group name="Object_2">
                            <group name="RootNode">
                                <group name="Circle_020" position={[0.038, 22, 0.089]} rotation={[-1.593, 0.017, 2.342]} scale={0.5}>
                                    <mesh name="Circle_020_corn_plant__corn_texture_png_0" geometry={nodes.Circle_020_corn_plant__corn_texture_png_0.geometry} material={materials.corn_plant__corn_texture_png} />
                                    <mesh name="Circle_020_corn_plant_001__corn_texture_png_001_0" geometry={nodes.Circle_020_corn_plant_001__corn_texture_png_001_0.geometry} material={materials.corn_plant_001__corn_texture_png_001} />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('../../modelos/corn.glb')
